mode: deployment

service:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"

resources:
  limits:
    cpu: 100m
    memory: 200M

config:
  exporters:
    otlp/tempo:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/tempo]
      metrics:
        receivers: [otlp]
        processors: [batch]
