# otel-collector-values.yaml
# THIS VERSION HAS CORRECT SPACING

# Corresponds to spec.mode
mode: deployment

# Corresponds to spec.service.annotations
service:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"

# Corresponds to spec.config
# All indentation here uses standard spaces.
config:
  receivers:
    prometheus:
      trim_metric_suffixes: true
      use_start_time_metric: true
      report_extra_scrape_metrics: true
      config:
        scrape_configs:
          - job_name: 'normal-otel-collector'
            scrape_interval: 5s
            static_configs:
              - targets: ['0.0.0.0:8888']
  exporters:
    otlp/tempo:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    
    prometheus:
      endpoint: "0.0.0.0:8889"

    logging:
      verbosity: detailed

  service:
    telemetry:
      metrics:
        address: "0.0.0.0:8888"
        level: detailed
        readers:
          - periodic:
              exporter:
                otlp:
                  endpoint: http://0.0.0.0:4318
                  protocol: http/protobuf

    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/tempo, logging]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus, logging]
