# helm-values/neo4j-values.yaml

# Note: The official Neo4j chart uses this structure.
# The structure you had was for the Bitnami chart.
# This version matches the chart you are using.

neo4j:
  name: neo4j-db
  password: "bitnami1"
  edition: "community"
  acceptLicenseAgreement: "no"
  resources:
    cpu: 0.5
    memory: 2Gi

volumes:
  data:
    mode: "defaultStorageClass"

    defaultStorageClass:
      accessModes:
        - ReadWriteOnce
      requests:
        storage: 10Gi
  # data:
  #   mode: "dynamic"
  #   dynamic:
  #     storageClassName: gp2