# otel-collector-values.yaml
# THIS VERSION HAS CORRECT SPACING

# Corresponds to spec.mode
mode: deployment

# Corresponds to spec.service.annotations
service:
  enabled: true
  type: ClusterIP
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"

# Corresponds to spec.config
# All indentation here uses standard spaces.
config:
  exporters:
    otlp/tempo:
      endpoint: "tempo.monitoring.svc.cluster.local:4317"
      tls:
        insecure: true
    
    prometheus:
      endpoint: "0.0.0.0:8889"

    logging:
      verbosity: detailed

  service:
    telemetry:
      metrics:
        address: "0.0.0.0:8888"
        level: detailed
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/tempo, logging]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [prometheus, logging]
